version: "3"
services:
    socket-server:
        build:
            context: ./flo_web/web_server/
    nginx:
        build:
            context: ./
            dockerfile: ./flo_web/Dockerfile
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - socket-server
        volumes:
            - ./certs:/etc/nginx/certs
