---
version: '3'
services:
  coturn:
    restart: unless-stopped
    build:
      context: ./flo_web/turn_server/
    env_file:
      - ./certs/coturn.env
    volumes:
      - ./certs/certbot/conf:/etc/letsencrypt
    network_mode: host
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./certs/certbot/conf:/etc/letsencrypt
      - ./certs/certbot/www:/var/www/certbot
    entrypoint: /bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 48h &
      wait $${!}; done;'
  nginx:
    build:
      context: ./
      dockerfile: ./flo_web/Dockerfile-turn
    ports:
      - 80:80
    restart: unless-stopped
    volumes:
      - ./certs/certbot/conf:/etc/letsencrypt
      - ./certs/certbot/www:/var/www/certbot
  datadog:
    restart: unless-stopped
    image: datadog/agent
    env_file:
      - ./certs/datadog.env
    environment:
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL=true
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_AC_EXCLUDE=image:datadog/agent
      - DD_PROCESS_AGENT_ENABLED=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
