version: "3"
services:
  host-server:
    env_file:
      - ./certs/session-secret.env
    build:
      context: ./flo_web/web_server/
    depends_on:
      - postgres
      - session-store
    command: ["node", "build/host.js"]
  operator-server:
    env_file:
      - ./certs/session-secret.env
    build:
      context: ./flo_web/web_server/
    depends_on:
      - postgres
      - session-store
    command: ["node", "build/operator.js"]
  api-server:
    env_file:
      - ./certs/session-secret.env
    build:
      context: ./flo_web/web_server/
    depends_on:
      - postgres
      - session-store
    command: ["node", "build/api.js"]
  nginx:
    build:
      context: ./
      dockerfile: ./flo_web/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - host-server
      - operator-server
      - api-server
    volumes:
      - ./certs:/etc/nginx/certs
  postgres:
    image: postgres
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
      - ./flo_web/web_server/database/setup:/docker-entrypoint-initdb.d
  session-store:
    image: redis
  client-store:
    image: redis
