version: "3"
# This docker compose file makes a few changes that make developing easier.
# Docker will automatically layer this over the docker-compose.yml base file
#
# The changes are 
#     - the addition of a node server that auto recompiles the front end
#     - Pulling in the nginx config from outside and using the develop instead of the production file
services:
    nginx:
        volumes:
            - ./certs/certbot/conf:/etc/letsencrypt
            - ./certs/certbot/www:/var/www/certbot
        command: "/bin/sh -c 'while :; do sleep $(( $(date -d 'sunday 0730' +%s) - (date +%s) )) & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    certbot:
        image: certbot/certbot
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep $(( $(date -d 'sunday 0630' +%s) - (date +%s) )) & wait $${!}; done;'"

