version: "3"
# This docker compose file makes a few changes that make developing easier.
# Docker will automatically layer this over the docker-compose.yml base file
#
# The changes are 
#     - the addition of a node server that auto recompiles the front end
#     - Pulling in the nginx config from outside and using the develop instead of the production file
services:
    dev-server: 
        build: 
            context: ./flo_web/web_app/ 
        environment:
            - CI=true
        volumes:
            - ./flo_web/web_app:/usr/src/app
    nginx:
        volumes:
            - ./flo_web/nginx-dev.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - dev-server
    socket-server:
        volumes:
            - ./flo_web/web_server:/usr/src/app
        command: ["npm", "run" ,"dev"]
    postgres:
        environment:
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=flodb
        ports:
            - 5432:5432
