FROM datadog/agent:latest
ADD conf/redisdb.yaml /etc/datadog-agent/conf.d/redisdb.d/conf.yaml
ADD conf/postgres.yaml /etc/datadog-agent/conf.d/postgres.d/conf.yaml
ADD conf/nginx.yaml /etc/datadog-agent/conf.d/nginx.d/conf.yaml
