FROM datadog/agent:latest
COPY conf/redisdb.yaml     /etc/datadog-agent/conf.d/redisdb.d/conf.yaml
COPY conf/postgres.yaml    /etc/datadog-agent/conf.d/postgres.d/conf.yaml
COPY conf/nginx.yaml       /etc/datadog-agent/conf.d/nginx.d/conf.yaml
