FROM datadog/agent:latest
COPY ./conf.d/nginx.d/conf.yaml     /etc/datadog-agent/conf.d/nginx.d/conf.yaml
COPY ./conf.d/postgres.d/conf.yaml     /etc/datadog-agent/conf.d/postgres.d/conf.yaml
COPY ./conf.d/redisdb.d/conf.yaml     /etc/datadog-agent/conf.d/redisdb.d/conf.yaml
